### ISSUE TITLE
about label(-1,nan)

### ISSUE THREAD

**Issue by aguang1201** [aligholami/CheXpert-Keras#1]
Thank you for your nice work.I downloaded the chexpert dataset too.I find the label in the train.csv had four values:-1,0,1,Nan.But in your train.csv,I saw that you changed -1 to 0.And because of nan value in the labels,the model still can't train a good results.what means of -1 and nan in the labels?

**Comment by aguang1201** [comment]
@aligholami Thank you for your explanation.I converted -1 and NaN to 0.And I trained the models, the results is:
1. Cardiomegaly: 0.8172075624304923
2. Edema: 0.9248456181842071
3. Consolidation: 0.9396491228070175
4. Pleural_Effusion: 0.9212289926796577

**Comment by aligholami** [comment]
@aguang1201 Glad to hear it worked.
